server:
  port: 8992

spring:
  banner:
    image:
      location: classpath:banner.txt

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximumPoolSize: 2
      minimumIdle: 1
      idleTimeout: 60000
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: false